// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzeephbaivzqsiycvyax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6ZWVwaGJhaXZ6cXNpeWN2eWF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0Mjc1MzMsImV4cCI6MjA2ODAwMzUzM30.UvZTaXRrCBbonLDkKrLTS3Oyicb1q5J-oe9a3nWcSxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});